"""update embedding dimension to 768

Revision ID: 9d4690a9aea9
Revises: c24377f9cecc
Create Date: 2026-04-10 19:22:09.093373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4690a9aea9'
down_revision: Union[str, None] = 'c24377f9cecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###