"""
CarePath — Triage Case Endpoints
==================================
The core of CarePath's medical functionality.

Routes:
  POST /cases              → open a new triage case
  GET  /cases/{id}         → get case details and priority
  POST /cases/{id}/evaluate → run the triage algorithm
  POST /cases/{id}/resolve  → close with recommendation
"""
from uuid import UUID

from fastapi import APIRouter, HTTPException, status

from src.models.enums import CaseStatus, TriagePriority
from src.models.symptom import Symptom
from src.models.triage import TriageCase, TriageCaseCreate

router = APIRouter(
    prefix="/cases",
    tags=["triage cases"],
)

# Temporary in-memory store
_cases_db: dict[UUID, TriageCase] = {}

@router.post(
    "/",
    response_model=TriageCase,
    status_code=status.HTTP_201_CREATED,
    summary="Open a new triage case",
    description="""
    Opens a new triage case with the patient's symptoms.
    
    The case starts with status OPEN.
    Call POST /cases/{id}/evaluate to run the triage algorithm
    and receive a priority level.
    """,
)
async def create_case(case_data: TriageCaseCreate) -> TriageCase:
    """
    POST /api/v1/cases
    
    Creates a TriageCase from the submitted data.
    Converts SymptomCreate objects to Symptom objects
    with generated IDs and timestamps.
    """
    # Create the case first to get its ID
    new_case = TriageCase(
        patient_id=case_data.patient_id,
        chief_complaint=case_data.chief_complaint,
    )

    # Convert SymptomCreate → Symptom
    # SymptomCreate has no ID or case_id
    # Symptom has both — created here with the case's ID
    symptoms = [
        Symptom(
            description=s.description,
            severity=s.severity,
            duration_hours=s.duration_hours,
            body_location=s.body_location,
            is_worsening=s.is_worsening,
            case_id=new_case.id,     # link symptom to this case
        )
        for s in case_data.symptoms  # list comprehension
    ]

    new_case.symptoms = symptoms
    _cases_db[new_case.id] = new_case

    return new_case

@router.get(
    "/{case_id}",
    response_model=TriageCase,
    summary="Get triage case details",
)
async def get_case(case_id: UUID) -> TriageCase:
    """GET /api/v1/cases/{case_id}"""
    case = _cases_db.get(case_id)
    if case is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Case {case_id} not found",
        )
    return case


@router.post(
    "/{case_id}/evaluate",
    response_model=TriageCase,
    summary="Run triage algorithm on this case",
    description="""
    Runs the START triage protocol on the case's symptoms.
    
    Returns the case with priority set to one of:
    - P1_immediate: life-threatening, go to ER now
    - P2_urgent: serious, urgent care within 1 hour
    - P3_delayed: moderate, can wait 1-2 hours
    - P4_minimal: minor, self-care appropriate
    
    Transitions status from OPEN to IN_REVIEW.
    """,
)
async def evaluate_case(case_id: UUID) -> TriageCase:
    """
    POST /api/v1/cases/{case_id}/evaluate
    
    This endpoint runs the core CarePath algorithm.
    In Lesson 5 (AI), this will also call the LLM
    to generate a natural language recommendation.
    """
    case = _cases_db.get(case_id)
    if case is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Case {case_id} not found",
        )

    if case.status != CaseStatus.OPEN:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Case is already {case.status.value} — cannot re-evaluate",
        )

    # Run the START protocol algorithm
    # This is the method you built in triage.py
    case.calculate_priority()

    # Auto-escalate P1 cases
    if case.priority == TriagePriority.P1_IMMEDIATE:
        case.escalate()

    return case


@router.post(
    "/{case_id}/resolve",
    response_model=TriageCase,
    summary="Resolve case with medical recommendation",
)
async def resolve_case(
    case_id: UUID,
    recommendation: str,
) -> TriageCase:
    """
    POST /api/v1/cases/{case_id}/resolve
    
    Closes the case with a medical recommendation.
    In Lesson 5 (AI), the recommendation will be
    generated by the LLM. For now, it's passed manually.
    """
    case = _cases_db.get(case_id)
    if case is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Case {case_id} not found",
        )

    if case.status != CaseStatus.IN_REVIEW:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Case must be IN_REVIEW before resolving",
        )

    case.resolve(recommendation)
    return case